services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data-source:/data-source
    env_file:
      - .env
    environment:
      RUN_MODE: api
    depends_on:
      - qdrant
      
  mcp:
      build:
        context: ./backend
      container_name: mcp_server
      restart: always
      ports:
        - "8080:8080"
      env_file:
        - ./backend/.env
      environment:
        RUN_MODE: mcp
      depends_on:
        - qdrant

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"   # Frontend accessible on localhost:3000
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml

configs:
  qdrant_config:
    content: |
      log_level: INFO